spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_competency?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
